package interfaz;
import dominio.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Agus
 */
public class VentanaMenuPrincipal extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaMenuPrincipal(Sistema modelo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modelo=modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnReplica = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setText("REGISTRAR JUGADOR");
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, 51));

        btnJugar.setText("JUGAR PARTIDA");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 51));

        btnReplica.setText("REPLICAR PARTIDA");
        jPanel1.add(btnReplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 250, 51));

        btnRanking.setText("RANKING JUGADORES");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        jPanel1.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 250, 51));

        btnSalir.setText("CERRAR JUEGO");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 153, 87));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/sumas.png"))); // NOI18N
        jLabel1.setLabelFor(jLabel1);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/720x1280-hd-wallpapers-zip.jpg"))); // NOI18N
        lblFondo.setLabelFor(lblFondo);
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 389, 658));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        VentanaJuego nuevoJuego = new VentanaJuego(modelo);

    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
         VentanaRanking ventanaRank = new VentanaRanking(modelo);
         ventanaRank.setVisible(true);
    }//GEN-LAST:event_btnRankingActionPerformed

  
    /*public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaMenuPrincipal dialog = new VentanaMenuPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReplica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
